### ISSUE TITLE
Workbook Pagination

### ISSUE THREAD

**Issue by jyorien** [xyntechx/NexLiber#22]
To improve the user experience, perhaps instead of displaying the workbook as one-page article, the workbook could be split into multiple pages with next/previous buttons. A table of contents would help the user navigate to the page they want to as well.

**Comment by xyntechx** [comment]
Good idea! I was thinking of adding a sidebar nav menu (see #15) a.k.a. a table of contents as you suggested. If you're interested, you can submit a PR to add the multipage + sidebar nav feature!

Also, if you want to create a Workbook as a NexLiber Creator, feel free to submit a PR at this repo and the [NexLiber Projects repo](https://github.com/xyntechx/NexLiber-Projects) too. I think Workbook(s) by you will be a great addition to the Library 😁

**Comment by xyntechx** [comment]
On second thought, maybe you can just implement the pagination feature first without the sidebar nav. I'll be integrating NexLiber with Sanity (#7) and the sidebar nav will be dependent on Sanity.

That aside, I'm looking forward to your Workbook (if you want to create one)! If you've got a Discord account, you can join NexLiber's server [here](https://nexliber.com/community).

**Comment by jyorien** [comment]
would love to help out after my assignments :)
